appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pxiq1n10dPNyHxJUUL7tukfCsFOLkEMyDuoQo7Bgu1dNT7CD1qtULRcYjJrh2yorqhofoo09Igzo1XYU5nAIjZlUmCnozghyuybI/zl4eZQpPpnHlmrO8DCbeSSUjkVwjvwG+5bz0QIQwy9dfr4NI3sOsLWW4v/06UKCiTMjSztUvHXOzVdzoUlGB7ShmpounKE4HxfFOp+ZqRDw8NoX4EQ803WUQy91ZOu1+JYux3cjhzosFzWyYk1cXrFHf+BCC0e0x/nPb2hcDOFv8Ad5cLj/9xwRO5AxL2b9lycbyEG6A2FenFbWUkuSl8ypenKXoGbbn18+moBX1IIu5ygt9/3GgBRAQQo9CGQ76+8YE4KNa3M58NtbcUcK0hiB9v5jj55iDMLH5nLKLpWn5QqGcxVUbkE5A4gR78zViKPXXSgKd96OjM/oi+2zOsGRcSMoxfaeRarmU+G4PE4a7FbO1MAOgk9mwSaG60qFSN+EefNcnd1TYKbsu+HK+wKX0Gzobqp7zGK1PzoN8FbUNhW0CFIVyiQm/lew5j78tMqhOo/u5SDnoUeLmUvfLEhRlrcj5qarUaIf9AEParrmyPGZA5L15AccJSHj4BDhlbP3Ir/K4rFRmHg44U5z4om3nTtWON8il0IC2bqi8/3TNIlJwYX6fmzohu4vrptgzyMErcA=}
