travis:
  secure:
    BINSTAR_TOKEN: sN8rUMGjs/3ixU2CNWsCHWW3wVg/asZvHUQ7cru9g2WpF7OT7niOIl/k0kKjmev4KId61kphrMatSyRxAQKtJs7nkGIlX3QQO9TyLcHTwqZ5ypv5jQpJqLb0pBaruLxI+lHhDE+pGYfZbtJFhlcfQJ104IuuaxVUcpQ1qOdcTewXRDLqdXBME/pvh34EstaLFl1kct0KfmSuCPgVH4/Hd8veDVpbymr0HSl4y6kEF1ejRiscsMUYCRemF390sNu4Jm4eHalhGFfCDBGAia2QzjJcLKfIHyIMbMA/saDC04WVTjIXGTj13BUGppYeNW1dYSR/sLTjLQOiu50nyahfirSQKVxbXaP8OLf6Xjho3ZWs5ugMRtRI60a6b0+x0B/OSnT/Qg3m2WyvkOkCRiCPPtOffrXdf1dwXswaMi734IZMMFqA4Gh47KHHCDzRXmAiMF5bYdnv9MZWsXIAXMTwm0O8pNX/GQ3u+IMnp8BFgcsMToeTYnqfGUfPC8/oavM6nIIV7Eb0C1de/06I5zJkad2VCL6i6l7gblWA/50oXLTKSq0c8c5CeErUZKZyhWNWdf1FuSCF+/l5I2rSSMPwQHlAGGXz/iPVlcj62hZqRj20OxyJPktZvwzpvlbVd7f5uEj2QjQ9IgrwCSS3ePaAuIdgi738ZE2R9vS3Sp4VP7g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
